In [ ]:
import numpy as np

#importar numpy

my_vector = np.array([2,5,6])
print(my_vector)

my_twovector = [2, 4]
print(np.array(my_twovector))

my_matrix = np.array([[2.5, 6.4] , [49.6, 56.9]])
print(my_matrix)

#Funcion arange
#genera un conjunto de numeros entre un valor inicial y uno final, y 
#si no se le escribe el tercer argumento, se entiende que el incremento es de 1
#start es inclusivo, stop es exclusivo
print(np.arange(start=2, stop= 20, step=3 ))
print(np.arange(start=200, stop= 10, step=-5 ))

#Funcion linspace
#genera un array
#los numeros son generados aleatoriamente
#en num pones la cantidad de numeros que deseas tener
#tanto start como stop son inclusivos
print(np.linspace(start= 3, stop= 100, num = 45))

#np.zeros son arrays vacios
#np.ones son valores pre-definidos
print(np.zeros(4))
print(np.zeros((3, 3, 3)))
#me imprime 3 de 3 columnas y 3 filas

print(np.zeros((2, 5, 6)))
#me imprime 2 de 5 filas y 6 columnas

print(np.ones((3, 4, 2)))
#me imprime 3 de 4 filas y 2 columnas

#np.full
#crea un array con un valor especifico 
#tiene 2 argumentos, shape = tupla con dimension y fill_value con el valor

print(np.full(shape=(4,6), fill_value=2))
#4 filas, 6 columnas, valor 2

print(np.full(shape=(3,4,5), fill_value=0.5))
#3, 4 filas, 5 columnas, valor 0.5

base = np.linspace(2,4,6)
print(base)
print(np.full_like(base, 6))
#tomo uno ya formado pero le paso un solo valor

print(np.full_like(base, np.pi))





[2 5 6]
[2 4]
[[ 2.5  6.4]
 [49.6 56.9]]
[ 2  5  8 11 14 17]
[200 195 190 185 180 175 170 165 160 155 150 145 140 135 130 125 120 115
 110 105 100  95  90  85  80  75  70  65  60  55  50  45  40  35  30  25
  20  15]
[  3.           5.20454545   7.40909091   9.61363636  11.81818182
  14.02272727  16.22727273  18.43181818  20.63636364  22.84090909
  25.04545455  27.25        29.45454545  31.65909091  33.86363636
  36.06818182  38.27272727  40.47727273  42.68181818  44.88636364
  47.09090909  49.29545455  51.5         53.70454545  55.90909091
  58.11363636  60.31818182  62.52272727  64.72727273  66.93181818
  69.13636364  71.34090909  73.54545455  75.75        77.95454545
  80.15909091  82.36363636  84.56818182  86.77272727  88.97727273
  91.18181818  93.38636364  95.59090909  97.79545455 100.        ]
[0. 0. 0. 0.]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e00223e1-940a-419b-854e-d5327f2e6aa8' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>